authenticate/urls.py
from django.urls import path
from . import views

app_name = "authenticate"

urlpatterns = [
    # Signup and login,logout
    path('signup/',views.signup,name='signup'),
    path('login/',views.Login,name="login"),
    path('logout/',views.Logout,name='logout'),
    # Profile
    path('profile/<int:pk>/',views.my_profile,name='profile'),
    path('profile/change/<int:pk>/',views.change_profile,name="change_profile"),
    path('porfile/photo/<int:pk>/',views.change_photo,name="change_photo"),
    path('porfile/password/<int:pk>/',views.ChangePassword,name="change_password"),
]

petsitting/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/',include('authenticate.urls')),
    path('',include('shop.urls')),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('grooming/',views.pet_grooming,name='pet_grooming'),
    path('boarding/',views.pet_boarding,name='pet_boarding'),
    path('walking/',views.pet_walking,name='pet_walking'),
    # temp links
    path('',views.home,name='home'),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('gallery/',views.gallery,name='gallery'),
    path('faqs/',views.faqs,name='faqs'),
    path('services/',views.services,name='services'),
]

authenticate/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class SignUp(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name="prof",null=True)
    image = models.ImageField(upload_to="profile_photos/",null=True)
    phone = models.CharField(blank=True,max_length=50)
    age = models.CharField(blank=True,max_length=5)
    address = models.TextField(blank=True)

class ContactUs(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(blank=True)
    subject = models.TextField(blank=True)
    message = models.TextField(blank=True)

authenticate/views.py
from django.shortcuts import render,reverse,redirect,get_object_or_404

# Models Import
from .models import SignUp
from django.contrib.auth.models import User

# Http Imports
from django.http import HttpResponse,HttpResponseRedirect

# Login imports
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

# Message Imports
from django.contrib import messages



# Create your views here.

# Sign,Login
def signup(request):
    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        phone = request.POST.get("phone")
        address = request.POST.get("address")
        age = request.POST.get("age")
        email = request.POST.get("email")
        username = request.POST.get("username")
        password = request.POST.get("password")
        image = request.FILES.get("image")

        user = User(first_name=first_name,last_name=last_name,username=username,email=email)
        user.set_password(password)
        user.save()
        user_extra = SignUp(phone=phone,address=address,age=age,user=user,image=image)
        user_extra.save()
        return HttpResponseRedirect('/authenticate/login/')
    return render(request,'authenticate/signup.html')

def Login(request):
    if request.method == 'POST':
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('shop:home'))
                #return HttpResponse("Logged IN")
            else:
                return HttpResponseRedirect("User is Not Active")
        else:
            messages.error(request,"User or Password is Invalid")
            return HttpResponseRedirect(reverse('authenticate:login'))
    return render(request,'authenticate/login.html')

def Logout(request):
    logout(request)
    return HttpResponseRedirect('/authenticate/login/')



# Profile Section
@login_required(login_url='/authenticate/login/')
def my_profile(request,pk):
    user = get_object_or_404(User,pk=pk)
    more_info = get_object_or_404(SignUp,pk=user.prof.pk)
    return render(request,"authenticate/profile.html",context={"user_info":user,"more_info":more_info})

def change_photo(request,pk):
    user = get_object_or_404(User,pk=pk)
    more_info = get_object_or_404(SignUp,pk=user.prof.pk)
    if request.method == "POST":
        image = request.FILES.get("image")
        more_info.image = image
        more_info.save()
        return HttpResponseRedirect(reverse('bag:Home'))
    return render(request,"authenticate/change_profile_photo.html")

@login_required(login_url='/authenticate/login/')
def change_profile(request,pk):
    user = get_object_or_404(User,pk=pk)
    more_info = get_object_or_404(SignUp,pk=user.prof.pk)
    if request.method == "POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        address =request.POST.get("address")


        # update
        user.username = username
        user.email = email
        more_info.phone = phone
        more_info.address = address

        user.save()
        more_info.save()
        return HttpResponseRedirect('/authenticate/profile/'+str(pk))
    return render(request,"authenticate/edit_profile.html",context={"user_info":user,"more_info":more_info})

@login_required(login_url='/authenticate/login/')
def ChangePassword(request,pk):
    user = get_object_or_404(User,pk=request.user.pk)
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password != confirm_password:
            messages.error(request,'Password does not matched')
            return redirect('/authenticate/login/')
        else:
            user.set_password(password)
            user.save()
    return render(request,'authenticate/change_password.html')

authenticate/templates/authenticate/change_password.html
<!doctype html>
{% load static %}
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

	<!-- CSS -->
	<link href="{% static 'assets/css/index.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/add_item.css' %}" rel="stylesheet">

    <!-- Icons -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">
<title> Grossary Bag </title>

      <!-- CSS -->
    <style>
.textbox {
    border: 1px solid #c4c4c4;
    height: 40px;
    width: 375px;
    font-size: 13px;
    padding: 4px 4px 4px 4px;
    border-radius: 4px;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    box-shadow: 0px 0px 8px #d9d9d9;
    -moz-box-shadow: 0px 0px 8px #d9d9d9;
    -webkit-box-shadow: 0px 0px 8px #d9d9d9;
}

.textbox:focus {
    outline: none;
    border: 1px solid #7bc1f7;
    box-shadow: 0px 0px 8px #7bc1f7;
    -moz-box-shadow: 0px 0px 8px #7bc1f7;
    -webkit-box-shadow: 0px 0px 8px #7bc1f7;
}
</style>
</head>
<body class="body-bg">

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg nav-bg p-4">
 <div class="container-fluid">
  <!-- Brand logo -->
   <a class="navbar-brand nav-text-color nav-brand-size">
    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-basket3" viewBox="0 0 16 16">
  <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z"/>
</svg>
    </a>
  <!-- End of Brand logo -->

  <!-- Toggler -->
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
   </button>
   <!-- End of Toggler -->

   <!-- Navbar contents -->
   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	 <!-- Home -->
	  <li class="nav-item ms-4">
	    <a class="nav-link active nav-text-color" href="{% url 'bag:Home' %}"> Home </a>
      </li>


		 {% if user.is_authenticated %}
          <!-- Profile -->
           <li class="nav-item ms-4">
               <a class="nav-link active nav-text-color" href="{% url 'authenticate:profile' pk=user.pk %}"> Profile </a>
           </li>

          {% endif %}
	 </ul>

	 <form class="d-flex" method="POST">
         {% csrf_token %}
        <input class="form-control me-2 text-muted" type="date" name="date">
        <button class="btn nav-text-color btn-outline-success" type="submit">Filter</button>
      </form>
       {% if user.is_authenticated %}
       <!-- Logout -->
          <li class="nav-item mb-4">
            <a class="nav-link active nav-text-color" href="{% url 'authenticate:logout' %}"> Logout </a>
          </li>
       {% else %}
       <li class="nav-item ms-4">
            <a class="nav-link active nav-text-color" href="{% url 'authenticate:login'  %}"> Login </a>
          </li>
       {% endif %}
   </div>
   <!-- End of navbar contents -->


 </div>
</nav>
<!-- End of Navigation Bar -->


  <!-- Sign UP -->
  <div class="registration-form social-media">
     <section>
        <form method="POST">
          {% csrf_token %}
            <div class="text-center pb-4">
                <span><h2>Change Password</h2></span>
            </div>
			<hr class="hr-primary mb-3" />
            <div class="form-group pt-4 text-center">
                <input type="password" name="password" placeholder="Password" required="" id="id_password" class="textbox">
                      <i class="far fa-eye" id="togglePassword" style="margin-left: -30px; cursor: pointer;"></i>
                <script>
                    const togglePassword = document.querySelector('#togglePassword');
                      const password = document.querySelector('#id_password');

                      togglePassword.addEventListener('click', function (e) {
                        // toggle the type attribute
                        const type = password.getAttribute('type') === 'password' ? 'text' : 'password';
                        password.setAttribute('type', type);
                        // toggle the eye slash icon
                        this.classList.toggle('fa-eye-slash');
                    });
                </script>
            </div>

			<div class="form-group pt-4 text-center">
                <input type="password" name="confirm_password" placeholder="Confirm Password" required="" id="confirm_password" class="textbox">
                      <i class="far fa-eye" id="tPassword" style="margin-left: -30px; cursor: pointer;"></i>
                <script>
                    const tPassword = document.querySelector('#tPassword');
                      const pass = document.querySelector('#confirm_password');

                      tPassword.addEventListener('click', function (e) {
                        // toggle the type attribute
                        const type = pass.getAttribute('type') === 'password' ? 'text' : 'password';
                        pass.setAttribute('type', type);
                        // toggle the eye slash icon
                        this.classList.toggle('fa-eye-slash');
                    });
                </script>
            </div>

            <div class="form-group pt-4">
                <button type="submit" class="btn btn-block create-account">Save</button>
            </div>
        </form>
     </section>
    </div>
  <!-- End of Signup -->





</body>

</html>

authenticate/templates/authenticate/edit_profile.html
<!doctype html>
{% load static %}
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

	<!-- CSS -->
	<link href="{% static 'assets/css/index.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/add_item.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
<!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
<title> Grossary Bag </title>
</head>
<body class="body-bg" style="font-family: 'Roboto', sans-serif;">

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg nav-bg p-4">
 <div class="container-fluid">
  <!-- Brand logo -->
   <a class="navbar-brand nav-text-color nav-brand-size">
    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-basket3" viewBox="0 0 16 16">
  <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z"/>
</svg>
    </a>
  <!-- End of Brand logo -->

  <!-- Toggler -->
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
   </button>
   <!-- End of Toggler -->

   <!-- Navbar contents -->
   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	 <!-- Home -->
	  <li class="nav-item ms-4">
	    <a class="nav-link active nav-text-color" href="{% url 'bag:Home' %}"> Home </a>
      </li>


		 {% if user.is_authenticated %}
          <!-- Profile -->
           <li class="nav-item ms-4">
               <a class="nav-link active nav-text-color" href="{% url 'authenticate:profile' pk=user.pk %}"> Profile </a>
           </li>

          {% endif %}
	 </ul>

	 <form class="d-flex" method="POST">
         {% csrf_token %}
        <input class="form-control me-2 text-muted" type="date" name="date">
        <button class="btn nav-text-color btn-outline-success" type="submit">Filter</button>
      </form>
       {% if user.is_authenticated %}
       <!-- Logout -->
          <li class="nav-item mb-4">
            <a class="nav-link active nav-text-color" href="{% url 'authenticate:logout' %}"> Logout </a>
          </li>
       {% else %}
       <li class="nav-item ms-4">
            <a class="nav-link active nav-text-color" href="{% url 'authenticate:login'  %}"> Login </a>
          </li>
       {% endif %}
   </div>
   <!-- End of navbar contents -->


 </div>
</nav>
<!-- End of Navigation Bar -->




<!-- Profile Section -->
   <div class="container mt-5 pt-5">
    <div class="main-body mt-5">

       <form method="POST">
         {% csrf_token %}
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                      {% if more_info.image %}
                    <img src="{{ more_info.image.url }}" alt="Admin" class="mt-4 rounded-circle" width="150">
                      {% else %}
                      <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="mt-4 rounded-circle" width="150">

                      {% endif %}
                      <div class="mt-3">
                      <h4>{{ user_info.first_name }} {{ user_info.last_name }}</h4>

                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">UserName</h6>
                    </div>
                    <div class="col-sm-4 text-secondary">
                      <input type="text" value="{{ user_info.username }}" class='form-control' name="username" required>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <input type="text" value="{{ user_info.email }}" class='form-control' name="email" required>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <input type="text" value="{{ more_info.phone }}" class="form-control" name="phone" required>
                    </div>
                  </div>
                  <hr>

                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <input type="text" value="{{ more_info.address }}" class="form-control" name="address" required>
                    </div>
                  </div>
                  <hr>
                  <!-- Submit Button -->
                  <div class="">
                    <input type="submit" class="btn btn-primary" value="Save">
                  </div>
                  <!-- end of Submit Button -->
                </div>
              </div>

            </div>
          </div>
       </form>
        </div>
    </div>
<!-- End of Profile Section -->





</body>
</html>

authenticate/templates/authenticate/profile.html
<!doctype html>
{% load static %}
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

	<!-- CSS -->
	<link href="{% static 'assets/css/index.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/add_item.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
<!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
<title> Grossary Bag </title>
</head>
<body class="body-bg" style="font-family: 'Roboto', sans-serif;">

<!-- Navigation Bar -->
<nav class="navbar navbar-expand-lg nav-bg p-4">
 <div class="container-fluid">
  <!-- Brand logo -->
   <a class="navbar-brand nav-text-color nav-brand-size">
    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-basket3" viewBox="0 0 16 16">
  <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z"/>
</svg>
    </a>
  <!-- End of Brand logo -->

  <!-- Toggler -->
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
   </button>
   <!-- End of Toggler -->

   <!-- Navbar contents -->
   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	 <!-- Home -->
	  <li class="nav-item ms-4">
	    <a class="nav-link active nav-text-color" href="{% url 'bag:Home' %}"> Home </a>
      </li>


		 {% if user.is_authenticated %}
          <!-- Profile -->
           <li class="nav-item ms-4">
               <a class="nav-link active nav-text-color" href="{% url 'authenticate:profile' pk=user.pk %}"> Profile </a>
           </li>

          {% endif %}
	 </ul>

	 <form class="d-flex" method="POST">
         {% csrf_token %}
        <input class="form-control me-2 text-muted" type="date" name="date">
        <button class="btn nav-text-color btn-outline-success" type="submit">Filter</button>
      </form>
       {% if user.is_authenticated %}
       <!-- Logout -->
          <li class="nav-item mb-4">
            <a class="nav-link active nav-text-color" href="{% url 'authenticate:logout' %}"> Logout </a>
          </li>
       {% else %}
       <li class="nav-item ms-4">
            <a class="nav-link active nav-text-color" href="{% url 'authenticate:login'  %}"> Login </a>
          </li>
       {% endif %}
   </div>
   <!-- End of navbar contents -->


 </div>
</nav>
<!-- End of Navigation Bar -->




<!-- Profile Section -->
   <div class="container mt-5 pt-5">
    <div class="main-body mt-5">

          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    {% if more_info.image %}
                    <img src="{{ more_info.image.url }}" alt="Admin" class="mt-4 img-fluid rounded-circle">
                    {% else %}
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="mt-4 img-fluid rounded-circle">
                    {% endif %}
                    <div class="mt-3">
                      <h4>{{ user_info.first_name }} {{ user_info.last_name }}</h4>

                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user_info.first_name }} {{ user_info.last_name }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user_info.email }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ more_info.phone }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Mobile</h6>
                    </div>

                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ more_info.address }}
                    </div>
                  </div>
                    <!-- Edit and Password -->
                    <hr>
                  <div class="row">
                    <div class="col-sm-4">
                        <a href="{% url 'authenticate:change_profile' pk=user.pk %}" class="btn btn-primary">Edit</a>
                    </div>

                    <div class="col-sm-4">
                        <a href="{% url 'authenticate:change_photo' pk=user.pk %}" class="btn btn-primary">Change Profile Photo</a>
                    </div>

                      <div class="col-sm-4">
                        <a href="{% url 'authenticate:change_password' pk=user.pk %}" class="btn btn-primary">Change Password</a>
                    </div>



                  </div>
                    <!-- End of edit and password -->
                </div>
              </div>

            </div>
          </div>
        </div>
    </div>
<!-- End of Profile Section -->











</body>
</html>