authenticate/urls.py
from django.urls import path
from . import views

app_name = "authenticate"

urlpatterns = [
    # Signup and login,logout
    path('signup/',views.signup,name='signup'),
    path('login/',views.Login,name="login"),
    path('logout/',views.Logout,name='logout'),
    # Profile
    path('profile/<int:pk>/',views.my_profile,name='profile'),
    path('profile/change/<int:pk>/',views.change_profile,name="change_profile"),
    path('porfile/photo/<int:pk>/',views.change_photo,name="change_photo"),
    path('porfile/password/<int:pk>/',views.ChangePassword,name="change_password"),
]

petsitting/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/',include('authenticate.urls')),
    path('',include('shop.urls')),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('grooming/',views.pet_grooming,name='pet_grooming'),
    path('boarding/',views.pet_boarding,name='pet_boarding'),
    path('walking/',views.pet_walking,name='pet_walking'),
    # temp links
    path('',views.home,name='home'),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('gallery/',views.gallery,name='gallery'),
    path('faqs/',views.faqs,name='faqs'),
    path('services/',views.services,name='services'),
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Pets(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='pets')
    pet_type = models.CharField(max_length=256)
    pet_age = models.IntegerField()
    pet_name = models.CharField(max_length=256)
    breed_name = models.CharField(max_length=256)
    pet_weight = models.CharField(max_length=256)



class PetGrooming(models.Model):
    pet_detail = models.ForeignKey(Pets,on_delete=models.CASCADE,related_name='pet_grooming')
    pet_service_type = models.CharField(max_length=256)

class PetBoarding(models.Model):
    pet_detail = models.ForeignKey(Pets,on_delete=models.CASCADE,related_name='pet_boarding')
    time = models.TimeField()
    meal = models.CharField(max_length=500)
    special_care = models.TextField()

class PetWalking(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='pet_walking')
    pet_detail = models.ForeignKey(Pets,on_delete=models.CASCADE)

shop/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect,reverse,get_object_or_404

# Razorpay Imports
from razorpay import Client
# Models Import
from .models import Pets,PetWalking,PetBoarding,PetGrooming
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

def pet_grooming(request):
    if request.method == "POST":
        name = request.POST.get('pet_name')
        age = request.POST.get('pet_age')
        breed_name = request.POST.get('breed_name')
        weight = request.POST.get('weight')
        type = request.POST.get('pet_type')
        service = request.POST.get('service')
        get_user = get_object_or_404(User,pk=request.user.pk)
        new_pet = Pets(user=get_user,pet_type=type,pet_age=age,pet_name=name,breed_name=breed_name,pet_weight=weight)
        new_pet.save()
        new_pet_groom = PetGrooming(pet_detail=new_pet,pet_service_type=service)
        new_pet_groom.save()
        return HttpResponse("Saved!!!!")
    return render(request,'pet_detail.html')

def pet_boarding(request):
    if request.method == "POST":
        name = request.POST.get('pet_name')
        age = request.POST.get('pet_age')
        breed_name = request.POST.get('breed_name')
        weight = request.POST.get('weight')
        type = request.POST.get('pet_type')
        time = request.POST.get('time')
        meal = request.POST.get('meal')
        special_care = request.POST.get('special_care')
        get_user = get_object_or_404(User, pk=request.user.pk)
        new_pet = Pets(user=get_user, pet_type=type, pet_age=age, pet_name=name, breed_name=breed_name,
                       pet_weight=weight)
        new_pet.save()
        new_boarding = PetBoarding(pet_detail=new_pet,time=time,meal=meal,special_care=special_care)
        new_boarding.save()

        return HttpResponse("Saved!!!!!!")
    return render(request,'pet_boarding.html')

@csrf_exempt
def pet_walking(request):
    if request.method == "POST":
        name = request.POST.get('pet_name')
        age = request.POST.get('pet_age')
        breed_name = request.POST.get('breed_name')
        weight = request.POST.get('weight')
        type = request.POST.get('pet_type')
        get_user = get_object_or_404(User, pk=request.user.pk)
        new_pet = Pets(user=get_user, pet_type=type, pet_age=age, pet_name=name, breed_name=breed_name,
                       pet_weight=weight)
        new_pet.save()
        walking_obj = PetWalking(user=get_user,pet_detail=new_pet)
        walking_obj.save()

        return HttpResponse("Saved!!!!!!")
    razorpay_order_id = Client(auth=('rzp_test_5oavlxNIw3XN70','3CYNikEOYjwXPlcHdAdIj4iV'))
    razorpay_order_id = razorpay_order_id.order.create({'amount':'1000','currency':'INR','payment_capture':'1'})
    context = {}
    context['razorpay_order_id'] = razorpay_order_id
    context['razorpay_merchant_key'] = 'rzp_test_5oavlxNIw3XN70'
    context['razorpay_amount'] = '5000'
    context['currency'] = 'INR'

    return render(request, 'pet_walking.html')

def home(request):
    razorpay_order_id = Client(auth=('rzp_test_5oavlxNIw3XN70', '3CYNikEOYjwXPlcHdAdIj4iV'))
    razorpay_order_id = razorpay_order_id.order.create({'amount': '1000', 'currency': 'INR', 'payment_capture': '1'})
    context = {}
    context['razorpay_order_id'] = razorpay_order_id
    context['razorpay_merchant_key'] = 'rzp_test_5oavlxNIw3XN70'
    context['razorpay_amount'] = '5000'
    context['currency'] = 'INR'

    return render(request,'index.html',context=context)

def gallery(request):
    razorpay_order_id = Client(auth=('rzp_test_5oavlxNIw3XN70', '3CYNikEOYjwXPlcHdAdIj4iV'))
    razorpay_order_id = razorpay_order_id.order.create({'amount': '1000', 'currency': 'INR', 'payment_capture': '1'})
    context = {}
    context['razorpay_order_id'] = razorpay_order_id
    context['razorpay_merchant_key'] = 'rzp_test_5oavlxNIw3XN70'
    context['razorpay_amount'] = '5000'
    context['currency'] = 'INR'
    return render(request,'Gallery.html',context=context)

def aboutus(request):
    razorpay_order_id = Client(auth=('rzp_test_5oavlxNIw3XN70', '3CYNikEOYjwXPlcHdAdIj4iV'))
    razorpay_order_id = razorpay_order_id.order.create({'amount': '1000', 'currency': 'INR', 'payment_capture': '1'})
    context = {}
    context['razorpay_order_id'] = razorpay_order_id
    context['razorpay_merchant_key'] = 'rzp_test_5oavlxNIw3XN70'
    context['razorpay_amount'] = '5000'
    context['currency'] = 'INR'
    return render(request,'ABOUT US.html',context=context)

def faqs(request):
    razorpay_order_id = Client(auth=('rzp_test_5oavlxNIw3XN70', '3CYNikEOYjwXPlcHdAdIj4iV'))
    razorpay_order_id = razorpay_order_id.order.create({'amount': '1000', 'currency': 'INR', 'payment_capture': '1'})
    context = {}
    context['razorpay_order_id'] = razorpay_order_id
    context['razorpay_merchant_key'] = 'rzp_test_5oavlxNIw3XN70'
    context['razorpay_amount'] = '5000'
    context['currency'] = 'INR'
    return render(request,'FAQs.html',context=context)

def services(request):
    razorpay_order_id = Client(auth=('rzp_test_5oavlxNIw3XN70', '3CYNikEOYjwXPlcHdAdIj4iV'))
    razorpay_order_id = razorpay_order_id.order.create({'amount': '50000', 'currency': 'INR', 'payment_capture': '1'})
    context = {}
    context['razorpay_order_id'] = razorpay_order_id
    context['razorpay_merchant_key'] = 'rzp_test_5oavlxNIw3XN70'
    context['razorpay_amount'] = '5000'
    context['currency'] = 'INR'
    return render(request,'Services.html',context=context)

shop/templates/ABOUT US.html
<html>
{% load static %}
<head>
	<!-- Bootstrap CSS -->
	 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
	</head>
<title>Aboutus</title>
	
<style>
  body{
background-color: lightblue;
color: black;
  }

	hr{
		color: black;
	}
	.about{height: 250px;font-size:35px;
		color: red;background-image: url("{% static 'about2.jpg' %}");
	}
	h1{background-color: beige;
      color: black;
	}
	.mission{margin-top: 20px;
		border-style: groove;border-color: brown;
		height: 170px;width: 730px;background-color:lawngreen;margin-left: 450px;
	}
	
	.list-unstyled{
		margin-left: 20px;
	}
	.media{
		margin-top: 5px;
	}.button{margin-top: 20px;margin-left: 600px;padding: 20px; column-gap: 10px;}
</style>

<body>
	<h1 align="center"><marquee scrollamount=10><u>ABOUT US</u></marquee></h1>
    <div class="about">

      <img src = "https://th.bing.com/th/id/R.4bfe363e78762605827adc8df9c4ba27?rik=5HxovXLqgv6dwA&riu=http%3a%2f%2fwww.exhiconworld.com%2fwp-content%2fuploads%2f2014%2f05%2fus1.png&ehk=FkrAgXejO5Mm7VcU72EPX%2bzyOAUgeItF1IYu50RyGj0%3d&risl=&pid=ImgRaw&r=0">


    	<!-- Our Mission Is To Give Proper Solutions To keep you relaxed while on Vacations without worrying for your pets.<br>
    And Provide Affordable & Boarding (grooming) Services From Our Professional Pet-sitters
    -->

    </div>

	<hr>
	  <h1 align="center"><i><marquee scrollamount=10><u>Our Duty</u></marquee></u></i></h1>
      <div class="mission">
	    <h4 align="center">"Your pet is part of your family, and thats how they treated .<br>
      Trustworthy local petsitters are the only kind you will and on our platform.<br>
    From a quick walk around the park to a month long vacation, you can find a petsitter with a right availability all year around."</h4></div></hr><br>

    <hr> 
      <h1 align="center"><i><marquee scrollamount=10><u>Our Team Members</u></marquee></u></i></h1>

    <ul class="list-unstyled">
  <li class="media">
    <!-- <img src="nature4.jpg" class="mr-3" alt="..."> -->
    <div class="media-body">
      <h5 class="mt-0 mb-1"><i><u>PRASAD PAWAR</u></i></h5>
      <p><i><b>NAME:</b>PRASAD PAWAR</i><br> student at Dr.DYPIT,Pimpri Pune.</p>
    </div>
  </li>
  <li class="media">
    <!-- <img src="nature4.jpg" class="mr-3" alt="..."> -->
    <div class="media-body">
      <h5 class="mt-0 mb-1"><i><u>AVADHESH VORA</u></i></h5>
      <p><i><b>NAME:</b>AVADHESH VORA</i><br> student at Dr.DYPIT,Pimpri Pune.</p>
    </div>
  </li>
  <!-- <li class="media my-4">
    <img src="pratik.jpg.jpg" class="mr-3" alt="...">
    <div class="media-body">
      <h5 class="mt-0 mb-1"><i><u>P</u></i></h5>
      <p>
      	<i><b>NAME:</b></i>AVADHESH VORA<br> working as a student at Dr.DYPIT,Pimpri Pune.
      </p>
    </div>
  </li> -->
  <li class="media">
    <!-- <img src="nature5.jpg" class="mr-3" alt="..."> -->
    <div class="media-body">
      <h5 class="mt-0 mb-1"><i><u>PRANAV DESHMUKH</u></i></h5>
      <p> <p><i><b>NAME:</b></i>PRANAV DESHMUKH<br> working as a student at Dr.DYPIT,Pimpri Pune.</p></p>
    </div>
  </li>
  <li class="media">
    <!-- <img src="nature4.jpg" class="mr-3" alt="..."> -->
    <div class="media-body">
      <h5 class="mt-0 mb-1"><i><u>SHARAYU KADAM</u></i></h5>
      <p> <p><i><b>NAME:</b></i>SHARAYU KADAM<br> working as a student at Dr.DYPIT,Pimpri Pune.</p></p>
    </div>
  </li>
  <li class="media">
    <!-- <img src="nature4.jpg" --><!--  class="mr-3" alt="..."> -->
    <div class="media-body">
      <h5 class="mt-0 mb-1"><i><u>FATIMA SAYYED</u></i></h5>
      <p> <p><i><b>NAME:</b></i>FATIMA SAYYED<br> working as a student at Dr.DYPIT,Pimpri Pune.</p></p>
    </div>
  </li>
</ul>

<hr>
   <h1 align="center"><i><marquee><u>OUR Pet-sitter</u></marquee></i></h1>
   
   <li class="media">
    <!-- <img src="nature4.jpg" class="mr-3" alt="..."> -->
    <div class="media-body">
      <h5 class="mt-0 mb-1"><u>Mr. VIKRAM SAHAI </u></h5>
      <p>His Motive is totally inclined towards the welfare of the pet animals and he studies how people treat them as his PRIMARY work.</p>
    </div>
  </li>

 
  <br>
  <hr>
  <div class="button">
<a href="{% url 'shop:home' %}"><button type="button" class="btn btn-outline-primary">Home</button></a>
<a href="{% url 'shop:faqs' %}"><button type="button" class="btn btn-outline-secondary">FAQs</button></a>
<a href="{% url 'shop:aboutus' %}"><button type="button" class="btn btn-outline-danger">About Us</button></a>


</body>

shop/templates/FAQs.html
<html>
{% load static %}
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

<title>
	faqs.html</title>
<style>
	body{
		background-color: mintcream;

	}
.link{
	margin-top: 50px;/*margin-left: 10px;margin-right: 10px*/;
	height: 350px;
	background-image: url("about-us-banner.jpg");
	color: white;opacity: 1.5;
	}
	h1{
		color: maroon;
	}
	.link2{
		height: 40px;
		background-color: skyblue;/*margin-left: 5px;margin-right:5px*/ ;
	}
	.link3{
       height: 60px;
       margin-left: 10px;/*margin-right: 10px*/;background-color: darkgrey;
	}
	.link4{
		margin-top: 20px;background-color: skyblue;
	}.link5{
       height: 60px;
       /*margin-left: 10px;margin-right: 10px;*/background-color:darkgrey;
	}
	h5{
		color: white;
	}
	.button{margin-top: 20px;margin-left: 600px;padding: 20px; column-gap: 10px;}
h4{
	color: black;
}
	
	

</style>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light nav">

  <a class="navbar-brand" href="{% url 'shop:home' %}"><b>Home</b></a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:aboutus' %}">AboutUs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:faqs' %}"><b>FAQs</b></a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'shop:gallery' %}">
        <b>Gallery</b>
        </a>
        </li>
		{% if user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link " href="{% url 'authenticate:logout' %}">
        <b>Logout</b>
        </a>
        </li>

          {% else %}
      </li>
        <li class="nav-item">
        <a class="nav-link " href="{% url 'authenticate:login' %}">
        <b>Login</b>
        </a>
        </li>
        {% endif %}

    </ul>
    

    </a>
   </div>
</nav>

	<div class="link"></div>
	<hr>
<h1 align="center">Frequently Asked Questions</h1>
<hr>
<div>

<div class="link2">
	<marquee direction=left scrollamount=10><h4 align="center">What is Petocare?</h4></marquee>
</div>

<div class="link3">
	<h5 align="center">Petocare is a pet-Sitting management System.We help people who are tensed by means of Their Pets while they are out of station or away from their Homes; here we provide easy accessibility to Pet-boarding Businessess.We provide these services 24 x 7 through our Online platform.
	</h5>
</div>
<!--***-->

<div class="link4">
	<marquee direction=left scrollamount=10><h4 align="center">Who will help?</h4></marquee>
</div>

<div class="link5">
	<h5 align="center">For your help, we are providing Proffesional Pet-sitters who will fulfill your objectives, preferences and type of breed you are having be it Dogs or cats .<br> </h5>
</div>
<!--***-->
<div class="link4">
	<marquee direction=left scrollamount=10><h4 align="center">What is Pricing structure ?</h4></marquee>
</div>

<div class="link5">
	<h5 align="center"> Yes! You read it right. The Prices are REASONABLE totally and we mean it. You get Charged according to the Services you get at no extra cost.</h5>
</div>
<!--***-->
<div class="link4">
	<marquee direction=left scrollamount=10><h4 align="center">Who is Main Pet- Sitter?</h4></marquee>
</div>

<div class="link5">
	<h5 align="center">Mr. Vikram Sahai and his team; Pet-Sitters are licenced, Trained and experienced person and professional Vetenary handling Experts. </h5>
</div>
<!--***-->
<div class="link4">
	<marquee direction=left scrollamount=10><h4 align="center">What will be the cost?</h4></marquee>
</div>

<div class="link5">
	<h5 align="center">You can pay online directly at our Website according your Packages and time duration you choose for your Loved-ones. 
	.</h5>
</div>
<!--***-->
<div class="link4">
	<marquee direction=left scrollamount=10><h4 align="center">How to communicate with our professionals?</h4></marquee>
</div>

<div class="link5">
	<h5 align="center"> By visiting the Locate the physical addresses or video call our People :<br><u> Exchanging Words with your Pet-Sitters</u> &emsp;&emsp; <u>Chatting online on your devices</u> &emsp;&emsp; <u>Speaking over with phone calls , Video Calls</u>
	</h5>
</div>
<!--***-->
<div class="link4">
	<marquee direction=left scrollamount=10><h4 align="center">Our Roles?</h4></marquee>
</div>

<div class="link5">
	<h5 align="center">We are providing these services on personalized Basis and <br> Our mission to build platform and making communication more better between user and your pets.</h5>
</div>
<!--***-->
<div class="link4">
	<marquee direction=left scrollamount=10><h4 align="center">How can we start?</h4></marquee>
</div>

<div class="link5">
	<h5 align="center">click <a href="{% url 'shop:home' %}"> Home </a> to start</h5>
</div>
<!--***-->

</div>

  <hr>
  <div class="button">
<a href="{% url 'shop:home' %}"><button type="button" class="btn btn-outline-primary">Home</button></a>
<a href="{% url 'shop:faqs' %}"><button type="button" class="btn btn-outline-secondary">FAQs</button></a>
<a href="{% url 'shop:aboutus' %}"><button type="button" class="btn btn-outline-danger">About Us</button></a>

</body>

</body></html>

shop/templates/pet_boarding.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="POST">
  {% csrf_token %}
  <input type="text" placeholder="Pet Name" name="pet_name"> <br>
  <input type="text" placeholder="Pet Age" name="pet_age"> <br>
  <input type="text" placeholder="Pet Type" name="pet_type"> <br>
  <input type="text" placeholder="Breed Name" name="breed_name"> <br>
  <input type="text" placeholder="Pet Weight" name="weight"> <br>
  <input type="time" placeholder="time" name="time"><br>
    <input type="text" placeholder="Meal" name="meal"><br>
    <input type="text" placeholder="special_care" name="special_care"><br>
    <input type="Submit" value="Submit">

</form>

</body>
</html>

shop/templates/pet_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="POST">
  {% csrf_token %}
  <input type="text" placeholder="Pet Name" name="pet_name"> <br>
  <input type="text" placeholder="Pet Age" name="pet_age"> <br>
  <input type="text" placeholder="Pet Type" name="pet_type"> <br>
  <input type="text" placeholder="Breed Name" name="breed_name"> <br>
  <input type="text" placeholder="Pet Weight" name="weight"> <br>
  <select name="service">
  <option value="Bathing">Bathing</option>
  <option value="Nail Trimming">Nail Trimming</option>
  <option value="Ear Cleaning">Ear Cleaning</option>
  <option value="Haricut">Haircut</option>
  </select>
    <input type="Submit" value="Submit">

</form>

</body>
</html>

shop/templates/pet_walking.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>

<form method="POST">
  {% csrf_token %}
  <input type="text" placeholder="Pet Name" name="pet_name"> <br>
  <input type="text" placeholder="Pet Age" name="pet_age"> <br>
  <input type="text" placeholder="Pet Type" name="pet_type"> <br>
  <input type="text" placeholder="Breed Name" name="breed_name"> <br>
  <input type="text" placeholder="Pet Weight" name="weight"> <br>

    <input type="Submit" value="Submit">
  <button id="rzp-button1">Pay</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_5oavlxNIw3XN70", // Enter the Key ID generated from the Dashboard
    "amount": "50000", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Pet Sitter",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "{{ razorpay_order_id }}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 2
    "handler": function (response){
        alert(response.razorpay_payment_id);
        alert(response.razorpay_order_id);
        alert(response.razorpay_signature)
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>
</form>

</body>
</html>